### ISSUE TITLE
ImportError: cannot import name log on openstack/keystone/stable/kilo.

### ISSUE THREAD

**Issue by Fuzi0n** [ging/keystone-oauth2-extension#6]
Hello,

I encounter an error while starting the uwsgi server. I followed the readme step by step and here's what i got in the log file:

```
Thu Mar  3 13:09:28 2016 - mapped 914320 bytes (892 KB) for 20 cores
Thu Mar  3 13:09:28 2016 - *** Operational MODE: preforking+threaded ***
2016-03-03 13:09:29.607 5784 CRITICAL keystone [-] ImportError: cannot import name log
2016-03-03 13:09:29.607 5784 TRACE keystone Traceback (most recent call last):
2016-03-03 13:09:29.607 5784 TRACE keystone   File "/var/www/keystone/admin", line 25, in <module>
2016-03-03 13:09:29.607 5784 TRACE keystone     application = wsgi_server.initialize_application(name)
2016-03-03 13:09:29.607 5784 TRACE keystone   File "/usr/lib/python2.7/dist-packages/keystone/server/wsgi.py", line 51, in initialize_application
2016-03-03 13:09:29.607 5784 TRACE keystone     startup_application_fn=loadapp)
2016-03-03 13:09:29.607 5784 TRACE keystone   File "/usr/lib/python2.7/dist-packages/keystone/server/common.py", line 41, in setup_backends
2016-03-03 13:09:29.607 5784 TRACE keystone     drivers = backends.load_backends()
2016-03-03 13:09:29.607 5784 TRACE keystone   File "/usr/lib/python2.7/dist-packages/keystone/backends.py", line 62, in load_backends
2016-03-03 13:09:29.607 5784 TRACE keystone     auth.controllers.load_auth_methods()
2016-03-03 13:09:29.607 5784 TRACE keystone   File "/usr/lib/python2.7/dist-packages/keystone/auth/controllers.py", line 69, in load_auth_methods
2016-03-03 13:09:29.607 5784 TRACE keystone     driver = importutils.import_object(plugin_class)
2016-03-03 13:09:29.607 5784 TRACE keystone   File "/usr/lib/python2.7/dist-packages/oslo_utils/importutils.py", line 38, in import_object
2016-03-03 13:09:29.607 5784 TRACE keystone     return import_class(import_str)(*args, **kwargs)
2016-03-03 13:09:29.607 5784 TRACE keystone   File "/usr/lib/python2.7/dist-packages/oslo_utils/importutils.py", line 27, in import_class
2016-03-03 13:09:29.607 5784 TRACE keystone     __import__(mod_str)
2016-03-03 13:09:29.607 5784 TRACE keystone   File "/usr/lib/python2.7/dist-packages/keystone/auth/plugins/oauth2.py", line 19, in <module>
2016-03-03 13:09:29.607 5784 TRACE keystone     from keystone.contrib.oauth2 import core as oauth2_core
2016-03-03 13:09:29.607 5784 TRACE keystone   File "/usr/lib/python2.7/dist-packages/keystone/contrib/oauth2/__init__.py", line 15, in <module>
2016-03-03 13:09:29.607 5784 TRACE keystone     from keystone.contrib.oauth2.core import *
2016-03-03 13:09:29.607 5784 TRACE keystone   File "/usr/lib/python2.7/dist-packages/keystone/contrib/oauth2/core.py", line 25, in <module>
2016-03-03 13:09:29.607 5784 TRACE keystone     from keystone.openstack.common import log
2016-03-03 13:09:29.607 5784 TRACE keystone ImportError: cannot import name log

```

I took a look at the directory structure, here's what I have (cf: http://pastebin.com/k2swcT6P).

Moreover, I can't tell if it's related but when I run the db_sync command I get: 

```
root@rcliment-storage01:/usr/lib/python2.7/dist-packages/keystone/common# keystone-manage db_sync --extension oauth2
2016-03-03 13:17:09.233 6268 CRITICAL keystone [-] ImportError: keystone.contrib.oauth2 extension does not exist.
2016-03-03 13:17:09.233 6268 TRACE keystone Traceback (most recent call last):
2016-03-03 13:17:09.233 6268 TRACE keystone   File "/usr/bin/keystone-manage", line 44, in <module>
2016-03-03 13:17:09.233 6268 TRACE keystone     cli.main(argv=sys.argv, config_files=config_files)
2016-03-03 13:17:09.233 6268 TRACE keystone   File "/usr/lib/python2.7/dist-packages/keystone/cli.py", line 585, in main
2016-03-03 13:17:09.233 6268 TRACE keystone     CONF.command.cmd_class.main()
2016-03-03 13:17:09.233 6268 TRACE keystone   File "/usr/lib/python2.7/dist-packages/keystone/cli.py", line 76, in main
2016-03-03 13:17:09.233 6268 TRACE keystone     migration_helpers.sync_database_to_version(extension, version)
2016-03-03 13:17:09.233 6268 TRACE keystone   File "/usr/lib/python2.7/dist-packages/keystone/common/sql/migration_helpers.py", line 249, in sync_database_to_version
2016-03-03 13:17:09.233 6268 TRACE keystone     _sync_extension_repo(extension, version)
2016-03-03 13:17:09.233 6268 TRACE keystone   File "/usr/lib/python2.7/dist-packages/keystone/common/sql/migration_helpers.py", line 201, in _sync_extension_repo
2016-03-03 13:17:09.233 6268 TRACE keystone     % package_name)
2016-03-03 13:17:09.233 6268 TRACE keystone ImportError: keystone.contrib.oauth2 extension does not exist.
2016-03-03 13:17:09.233 6268 TRACE keystone 
```

My distro is: ubuntu 14.04 and openstack kilo.

Thanks.

**Comment by federicofdez** [comment]
Hi @Fuzi0n,

This Keystone extension is actually an old version, and unfortunately we haven't planned to develop a stable one within a short-term period. For this reason, you may encounter issues like this one when trying to incorporate it to your Keystone installation.

We'll come back to you if we eventually make it work. In the meantime, you can check our [Keystone fork repo](https://github.com/ging/keystone), where we have a working OAuth2 extension.

Best regards,

**Comment by federicofdez** [comment]
@Fuzi0n 

By the way, if you manage to fix it, we'll be happy to merge your pull request.
Thanks!!

**Comment by federicofdez** [comment]
Closed for inactivity.

BR
